"""MithrilUI build entry point.

    python tools/build.py                                  # default profile
    python tools/build.py --profile declutter --resolution 2560x1440
    python tools/build.py --theme mithril-ash
    python tools/build.py --all                            # every profile x theme

Output lands in dist/skins/<FolderName>/ ready to copy into
Documents\\The Lord of the Rings Online\\ui\\skins\\.
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

import gen_art
import gen_lua
import gen_skin
import validate
from theme import Theme, discover

ROOT = Path(__file__).resolve().parent.parent
THEMES_DIR = ROOT / "themes"
PROFILES_DIR = ROOT / "profiles"
SKIN_DIR = ROOT / "skin"
DIST_DIR = ROOT / "dist" / "skins"


def load_profile(name: str) -> dict:
    path = PROFILES_DIR / f"{name}.json"
    if not path.exists():
        available = ", ".join(sorted(p.stem for p in PROFILES_DIR.glob("*.json")))
        raise SystemExit(f"No profile '{name}'. Available: {available}")
    with path.open(encoding="utf-8") as handle:
        return json.load(handle)


def detect_resolution() -> list[int]:
    """Read the resolution out of LOTRO's own UserPreferences.ini.

    Getting this wrong is the single easiest way to end up with a toolbar in
    the wrong place, and the answer is sitting in a file we can already find.
    """
    import install  # local import: only needed for --resolution auto

    game_dir = install.find_game_dir()
    prefs = game_dir / "UserPreferences.ini"
    if not prefs.exists():
        raise SystemExit(
            f"No UserPreferences.ini in {game_dir}. "
            "Start the game once, or pass an explicit --resolution."
        )

    text = prefs.read_text(encoding="utf-8", errors="replace")
    # Prefer the active mode's value; fall back to whichever key is present.
    for key in ("WindowedResolution", "Resolution"):
        match = re.search(rf"^{key}\s*=\s*(\d+)\s*[xX]\s*(\d+)", text, re.MULTILINE)
        if match:
            return [int(match.group(1)), int(match.group(2))]

    raise SystemExit(
        f"Could not find a Resolution entry in {prefs}. Pass --resolution WxH."
    )


def parse_resolution(text: str) -> list[int]:
    if text.strip().lower() == "auto":
        resolution = detect_resolution()
        print(f"detected resolution {resolution[0]}x{resolution[1]} from UserPreferences.ini")
        return resolution
    for separator in ("x", "X", "*", ","):
        if separator in text:
            width, height = text.split(separator, 1)
            return [int(width.strip()), int(height.strip())]
    raise SystemExit(f"Cannot read resolution '{text}'. Use e.g. 1920x1080, or 'auto'.")


def folder_name(profile: dict, theme: Theme) -> str:
    base = "MithrilUI"
    parts = [base]
    if theme.id != "mithril-dark":
        parts.append(theme.id.replace("mithril-", "").capitalize())
    if profile["id"] != "default":
        parts.append(profile["id"].capitalize())
    return "-".join(parts)


def skin_display_name(profile: dict, theme: Theme) -> str:
    name = theme.name
    if profile["id"] != "default":
        name += f" ({profile['id'].capitalize()})"
    return name


def write_readme(target: Path, profile: dict, theme: Theme, art_count: int, layout_used: list[str]) -> None:
    resolution = profile.get("resolution", [1920, 1080])
    lines = [
        f"{skin_display_name(profile, theme)}",
        "=" * len(skin_display_name(profile, theme)),
        "",
        "Generated by MithrilUI -- https://github.com/Felix-Helleckes/MithrilUI",
        "",
        f"  theme       {theme.id} ({theme.name})",
        f"  profile     {profile['id']}",
        f"  built for   {resolution[0]}x{resolution[1]}",
        f"  art assets  {art_count}",
        f"  layout      {', '.join(layout_used) if layout_used else 'none (art only)'}",
        "",
        "Install",
        "-------",
        "1. Copy this whole folder into:",
        "     Documents\\The Lord of the Rings Online\\ui\\skins\\",
        "2. Restart the game client. Skins are only read at startup.",
        "3. Options (Ctrl+O) -> UI Settings -> Current User Skin -> pick it.",
        "",
        "If the skin does not appear in the list, SkinDefinition.xml failed to",
        "parse. Run: python tools/validate.py <this folder>",
        "",
        "Do not edit SkinDefinition.xml here -- it is generated. Change the",
        "theme or profile JSON in the repo and rebuild.",
    ]
    (target / "README.txt").write_text("\n".join(lines) + "\n", encoding="utf-8")


def build_one(
    profile: dict,
    theme: Theme,
    rle: bool = False,
    clean: bool = True,
    verbose: bool = False,
) -> tuple[Path, list[str]]:
    target = DIST_DIR / folder_name(profile, theme)
    if clean and target.exists():
        shutil.rmtree(target)
    target.mkdir(parents=True, exist_ok=True)

    modules = set(profile.get("artModules", []))
    print(f"\n>> {folder_name(profile, theme)}")
    print(f"   theme {theme.id} | profile {profile['id']} | "
          f"{profile['resolution'][0]}x{profile['resolution'][1]}")

    started = time.perf_counter()
    art_records = gen_art.generate(
        SKIN_DIR / "assets.json", theme, target, modules=modules, rle=rle, verbose=verbose
    )
    total_bytes = sum(r["bytes"] for r in art_records)
    print(f"   art      {len(art_records)} assets, {total_bytes / 1024 / 1024:.1f} MB "
          f"({time.perf_counter() - started:.1f}s)")

    # The sweep flattens everything the hand-written manifest misses, which is
    # most of the interface: the documented dictionary covers about 5% of it.
    if "sweep" in modules:
        explicit_ids = {entry["id"] for entry in gen_art.load_manifest(SKIN_DIR / "assets.json")}
        sweep_records, stats = gen_art.generate_sweep(
            SKIN_DIR / "dictionary.txt",
            SKIN_DIR / "sweep.json",
            theme,
            target,
            explicit_ids=explicit_ids,
            rle=rle,
            catch_all=profile.get("options", {}).get("sweepCatchAll", True),
            debug=profile.get("options", {}).get("sweepDebug", False),
            verbose=verbose,
        )
        art_records = art_records + sweep_records
        sweep_bytes = sum(r["bytes"] for r in sweep_records)
        print(f"   sweep    {stats['swept']} mappings over "
              f"{len({r['file'] for r in sweep_records})} shared fills "
              f"({sweep_bytes / 1024:.0f} KB)")
        print(f"            {stats['excluded']} left alone (icons, state colours), "
              f"{stats['explicit']} already hand-tuned, "
              f"{stats['catchAll']} via catch-all"
              + (f", {stats['unmatched']} unmatched" if stats["unmatched"] else ""))

    layout_xml, layout_used = gen_skin.render_layout_modules(
        SKIN_DIR / "layout", profile.get("layoutModules", []), profile
    )
    print(f"   layout   {', '.join(layout_used) if layout_used else 'none'}")

    gen_skin.write_skin_definition(
        target / "SkinDefinition.xml",
        skin_display_name(profile, theme),
        art_records,
        layout_xml,
        header_note=f"MithrilUI | theme={theme.id} profile={profile['id']} "
                    f"res={profile['resolution'][0]}x{profile['resolution'][1]}",
    )
    write_readme(target, profile, theme, len(art_records), layout_used)
    return target, layout_used


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Build MithrilUI skins from themes, profiles and recipes.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument("--profile", default="default", help="profile name (default: default)")
    parser.add_argument("--theme", help="theme id, overrides the profile's choice")
    parser.add_argument("--resolution",
                        help="screen resolution, e.g. 2560x1440, or 'auto' to read it "
                             "from LOTRO's UserPreferences.ini")
    parser.add_argument("--all", action="store_true", help="build every profile x theme combination")
    parser.add_argument("--rle", action="store_true",
                        help="RLE-compress TGAs (much smaller; verify in-game before relying on it)")
    parser.add_argument("--no-validate", action="store_true", help="skip the post-build check")
    parser.add_argument("--no-lua", action="store_true",
                        help="do not refresh the shared palette in plugins/MithrilUI/Core")
    parser.add_argument("--list", action="store_true", help="list available themes and profiles")
    parser.add_argument("-v", "--verbose", action="store_true", help="print every generated asset")
    args = parser.parse_args(argv)

    themes = discover(THEMES_DIR)
    profiles = sorted(p.stem for p in PROFILES_DIR.glob("*.json"))

    if args.list:
        print("Themes:")
        for theme_id, path in themes.items():
            print(f"  {theme_id:<16} {Theme.load(path).name}")
        print("\nProfiles:")
        for name in profiles:
            print(f"  {name}")
        return 0

    combinations: list[tuple[dict, Theme]] = []
    if args.all:
        for profile_name in profiles:
            for theme_id, theme_path in themes.items():
                profile = load_profile(profile_name)
                if args.resolution:
                    profile["resolution"] = parse_resolution(args.resolution)
                combinations.append((profile, Theme.load(theme_path)))
    else:
        profile = load_profile(args.profile)
        if args.resolution:
            profile["resolution"] = parse_resolution(args.resolution)
        theme_id = args.theme or profile.get("theme", "mithril-dark")
        if theme_id not in themes:
            raise SystemExit(f"No theme '{theme_id}'. Available: {', '.join(themes)}")
        combinations.append((profile, Theme.load(themes[theme_id])))

    built: list[Path] = []
    for profile, theme in combinations:
        target, _ = build_one(profile, theme, rle=args.rle, verbose=args.verbose)
        built.append(target)

    # Keep the Lua palette in step with the skin. With --all there is no single
    # answer, so the last theme built wins; that is the one you were looking at.
    if not args.no_lua:
        lua_theme = combinations[-1][1]
        gen_lua.generate(lua_theme)
        print(f"\npalette   plugins/MithrilUI/Core/ThemeColors.lua <- {lua_theme.id}")

    if args.no_validate:
        print(f"\nBuilt {len(built)} skin(s) into {DIST_DIR}")
        return 0

    print("\n-- validating --")
    failed = 0
    for target in built:
        report = validate.validate_skin(target, reference_ids=ROOT / "docs" / "reference-element-ids.txt")
        report.print_summary()
        if report.errors:
            failed += 1

    print(f"\nBuilt {len(built)} skin(s) into {DIST_DIR}")
    if failed:
        print(f"{failed} skin(s) have errors -- see above.")
        return 1
    print("Next: python tools/install.py   (or copy the folder yourself)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
